import assert from 'node:assert/strict';
import { validateDataset, boxesAt, emptyReview, assign, identityAt, validateReview, importEvents, eventPatches, parseTime } from '../apps/web/public/fpa-cv/core.mjs';

const box = (id,x) => ({id,box:[x,.2,x+.1,.4],confidence:.8});
const data = validateDataset({schema:'fpa-tracks/v1',datasetId:'run-a',video:{name:'fixture.mp4',fps:30,width:1920,height:1080,duration:50,clipStart:25,clipEnd:26},detector:{sampleFps:10},frames:[{t:25,boxes:[box(1,.1),box(2,.6)]},{t:25.1,boxes:[box(1,.2)]},{t:25.2,boxes:[]},{t:25.5,boxes:[box(1,.5),box(2,.7)]}],tracks:[]});
assert.equal(data.tracks.length,2);
assert(Math.abs(boxesAt(data,25.05).find(b=>b.id===1).box[0]-.15)<1e-8);
assert.equal(boxesAt(data,24).length,0);
assert.equal(boxesAt(data,26).length,0);
assert.equal(boxesAt(data,25.35).length,0,'No phantom boxes through detection gaps');
assert.equal(boxesAt(data,25.25).length,0);
assert.equal(boxesAt(data,25.9).length,0,'Do not hold a stale final frame');

let review=emptyReview(data);
review=assign(review,data,1,25,25.6,{team:'home',jersey:'10'});
review=assign(review,data,1,25.2,25.6,{team:'away',jersey:'7'});
assert.equal(identityAt(review,1,25.19999).jersey,'10');
assert.equal(identityAt(review,1,25.2).jersey,'7','ID switch starts at exact boundary');
assert.equal(identityAt(review,1,25.6),null,'Intervals are half-open');
review=assign(review,data,1,25.3,25.4,null);
assert.equal(identityAt(review,1,25.35),null);
assert.equal(identityAt(review,1,25.45).jersey,'7','Partial removal preserves both sides');
review=assign(review,data,2,25,25.6,{team:'home',jersey:'10'});
assert.equal(identityAt(review,2,25.4).jersey,'10','One player may span several fragmented tracks');
assert.throws(()=>assign(review,data,999,25,25.5,{team:'home',jersey:'1'}));
assert.throws(()=>assign(review,data,1,25.5,25.4,{team:'home',jersey:'1'}));
assert.throws(()=>assign(review,data,1,0,25.4,{team:'home',jersey:'1'}));
assert.throws(()=>assign(review,data,1,25,25.4,{team:'home',jersey:'<script>'}));
assert.throws(()=>validateReview({...review,datasetId:'run-b'},data),'Assignments cannot cross run IDs');
assert.throws(()=>validateReview({...review,segments:[...review.segments,review.segments[0]]},data));

const row={Team:'home',Player:'9',Receiver:'6',Action:'Pass',Half:'1H',Time:'00:25',StatInput:'9ss6',Coord:'Pos(10, 5)',SceneState:'{"beforeDots":[{"number":"9"}]}',xG:'0.4'};
review.events=importEvents({rows:[row],logs:['original log']});
review.links={'0':{actor:{trackId:1,time:25.05},receiver:{trackId:2,time:25.5}}};
const exported=eventPatches(review);
assert.equal(exported[0].actor.jersey,'10');
assert.equal(exported[0].receiver.jersey,'10');
assert.deepEqual(exported[0].original,row,'FPA input, coordinates, scene state and metrics are immutable');
assert.equal(exported[0].originalLog,'original log');
const changed=assign(review,data,1,25,25.1,{team:'home',jersey:'11'});
assert.equal(eventPatches(changed)[0].actor.jersey,'11','Linked events resolve identity at their evidence timestamp');
const cleared=assign(changed,data,1,25,25.1,null);
assert.equal(eventPatches(cleared)[0].actor.status,'unresolved','Removing identity cannot leave a stale player');
assert.deepEqual(validateReview(JSON.parse(JSON.stringify(review)),data),review);
assert.throws(()=>validateReview({...review,links:{0:{actor:{trackId:1,time:25.35}}}},data));
assert.equal(parseTime('01:02.5'),62.5);assert.equal(parseTime('1:02:03'),3723);assert.equal(parseTime('01:60'),null);assert.equal(parseTime(''),null);assert.equal(parseTime(-1),null);
assert.throws(()=>validateDataset({...data,frames:[data.frames[1],data.frames[0]]}));
assert.throws(()=>validateDataset({...data,frames:[{t:25,boxes:[box(1,.1),box(1,.4)]}]}));
console.log('PASS: tracking gaps, time alignment, interval corrections, fragmented identities, run isolation, review roundtrip, event identity propagation and immutable FPA source.');
