server {
  listen 80;
  server_name stream.fineludens.kr _;

  add_header Access-Control-Allow-Origin * always;
  add_header Cache-Control no-cache;

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  location /hls/ {
    types {
      application/vnd.apple.mpegurl m3u8;
      video/mp2t ts;
    }
    root /srv;
    add_header Cache-Control no-cache;
    add_header Access-Control-Allow-Origin *;
    expires -1;
  }

  location / {
    return 200 'gateway up';
    add_header Content-Type text/plain;
  }
}

server {
  listen 443 ssl http2;
  server_name stream.fineludens.kr;

  ssl_certificate /etc/letsencrypt/live/stream.fineludens.kr/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/stream.fineludens.kr/privkey.pem;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_session_cache shared:SSL:10m;
  ssl_session_timeout 1d;
  ssl_prefer_server_ciphers off;

  add_header Access-Control-Allow-Origin * always;
  add_header Cache-Control no-cache;

  location /hls/ {
    types {
      application/vnd.apple.mpegurl m3u8;
      video/mp2t ts;
    }
    root /srv;
    add_header Cache-Control no-cache;
    add_header Access-Control-Allow-Origin *;
    expires -1;
  }

  location / {
    return 200 'stream gateway up';
    add_header Content-Type text/plain;
  }
}
