server {
  listen 80;
  server_name _;

  add_header Access-Control-Allow-Origin * always;
  add_header Cache-Control no-cache;

  location /hls/ {
    types {
      application/vnd.apple.mpegurl m3u8;
      video/mp2t ts;
    }
    root /srv;
    add_header Cache-Control no-cache;
    add_header Access-Control-Allow-Origin *;
    expires -1;
  }

  location / {
    return 200 'gateway up';
    add_header Content-Type text/plain;
  }
}
